[build]
  command = "
    cd .. && 
    npm ci && 
    
    cd packages/react-json-input && 
    npm i &&
    npm run build && 
    
    cd ../antd && 
    npm i &&
    npm run build && 
    
    cd ../../demo && 
    npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"