name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  install-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/package.json', 'packages/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
  packages:
    needs: install-react
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [react-json-input, antd]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/package.json', 'packages/package-lock.json') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          npm ci
          npm run test:ci
        working-directory: packages/${{matrix.folder}}
