name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  install-react-json-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-react-json-input-node-modules-2
        with:
          path: packages/react-json-input/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: packages/react-json-input
  install-react-json-input-antd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-react-json-input-antd-node-modules-2
        with:
          path: packages/antd/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/antd/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: packages/antd
  install-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-demo-node-modules
        with:
          path: demo/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('demo/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: demo
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
  test-react-json-input:
    needs: [install, install-react-json-input]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input
        env:
          cache-name: cache-react-json-input-node-modules-2
        with:
          path: packages/react-json-input/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input/package-lock.json') }}
      - if: steps.cache.outputs.cache-hit != 'true' || steps.cache-react-json-input.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm run test:ci
        working-directory: packages/react-json-input
  lint-react-json-input:
    needs: [install, install-react-json-input]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input
        env:
          cache-name: cache-react-json-input-node-modules-2
        with:
          path: packages/react-json-input/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input/package-lock.json') }}
      - if: steps.cache.outputs.cache-hit != 'true' || steps.cache-react-json-input.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm run lint
        working-directory: packages/react-json-input
  build-react-json-input:
    needs: [install, install-react-json-input]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input
        env:
          cache-name: cache-react-json-input-node-modules-2
        with:
          path: packages/react-json-input/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input/package-lock.json') }}
      - if: steps.cache.outputs.cache-hit != 'true' || steps.cache-react-json-input.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/cache@v2
        id: cache-react-json-input-dist
        env:
          cache-name: cache-react-json-input-dist
        with:
          path: packages/react-json-input/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - if: steps.cache-react-json-input-dist.outputs.cache-hit != 'true'
        run: npm run build
        working-directory:
          packages/react-json-input
  lint-antd:
    needs: [install, install-react-json-input, install-react-json-input-antd, build-react-json-input]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input
        env:
          cache-name: cache-react-json-input-node-modules-2
        with:
          path: packages/react-json-input/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input/package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input-antd
        env:
          cache-name: cache-react-json-input-antd-node-modules-2
        with:
          path: packages/antd/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/antd/package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input-dist
        env:
          cache-name: cache-react-json-input-dist
        with:
          path: packages/react-json-input/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input') }}
      - if: 
          steps.cache.outputs.cache-hit != 'true' || 
          steps.cache-react-json-input.outputs.cache-hit != 'true' || 
          steps.cache-react-json-input-antd.outputs.cache-hit != 'true' ||
          steps.cache-react-json-input-dist.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm run lint
        working-directory: packages/antd
  test-antd:
    needs: [install, install-react-json-input, install-react-json-input-antd, build-react-json-input]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input
        env:
          cache-name: cache-react-json-input-node-modules-2
        with:
          path: packages/react-json-input/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input/package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input-antd
        env:
          cache-name: cache-react-json-input-antd-node-modules-2
        with:
          path: packages/antd/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/antd/package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input-dist
        env:
          cache-name: cache-react-json-input-dist
        with:
          path: packages/react-json-input/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input') }}
      - if: 
          steps.cache.outputs.cache-hit != 'true' || 
          steps.cache-react-json-input.outputs.cache-hit != 'true' || 
          steps.cache-react-json-input-antd.outputs.cache-hit != 'true' ||
          steps.cache-react-json-input-dist.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm run test:ci
        working-directory: packages/antd
  build-react-json-input-antd:
    needs: [install, install-react-json-input, install-react-json-input-antd, build-react-json-input]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input
        env:
          cache-name: cache-react-json-input-node-modules-2
        with:
          path: packages/react-json-input/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input/package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input-antd
        env:
          cache-name: cache-react-json-input-antd-node-modules-2
        with:
          path: packages/antd/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/antd/package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input-dist
        env:
          cache-name: cache-react-json-input-dist
        with:
          path: packages/react-json-input/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input') }}
      - if: 
          steps.cache.outputs.cache-hit != 'true' || 
          steps.cache-react-json-input.outputs.cache-hit != 'true' || 
          steps.cache-react-json-input-antd.outputs.cache-hit != 'true' ||
          steps.cache-react-json-input-dist.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/cache@v2
        id: cache-react-json-input-antd-dist
        env:
          cache-name: cache-react-json-input-antd-dist
        with:
          path: packages/antd/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/antd') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - if: steps.cache-react-json-input-antd-dist.outputs.cache-hit != 'true'
        run: npm run build
        working-directory:
          packages/antd
  lint-demo:
    needs: [install, install-react-json-input, install-react-json-input-antd, install-demo, build-react-json-input, build-react-json-input-antd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input
        env:
          cache-name: cache-react-json-input-node-modules-2
        with:
          path: packages/react-json-input/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input/package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input-antd
        env:
          cache-name: cache-react-json-input-antd-node-modules-2
        with:
          path: packages/antd/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/antd/package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-demo
        env:
          cache-name: cache-demo-node-modules
        with:
          path: demo/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('demo/package-lock.json') }}
      - uses: actions/cache@v2
        id: cache-react-json-input-dist
        env:
          cache-name: cache-react-json-input-dist
        with:
          path: packages/react-json-input/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input') }}
      - uses: actions/cache@v2
        id: cache-react-json-input-antd-dist
        env:
          cache-name: cache-react-json-input-antd-dist
        with:
          path: packages/antd/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/antd') }}
      - if: 
          steps.cache.outputs.cache-hit != 'true' || 
          steps.cache-react-json-input.outputs.cache-hit != 'true' || 
          steps.cache-react-json-input-antd.outputs.cache-hit != 'true' ||
          steps.cache-demo.outputs.cache-hit != 'true' ||
          steps.cache-react-json-input-dist.outputs.cache-hit != 'true' ||
          steps.cache-react-json-input-antd-dist.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm run lint
        working-directory: demo