name: Test
on:
  push:
    branches: [ main, tests ]
  pull_request:
    branches: [ main ]
jobs:
  install-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: packages/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/package.json', 'packages/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: packages
  react-json-input:
    needs: install-react
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: packages/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/package.json', 'packages/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          npm ci
          npm test
        working-directory: packages/react-json-input
