name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  install-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
  test-react-json-input:
    needs: install-react
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          npm ci
          npm run test:ci
        working-directory: packages/react-json-input
  lint-react-json-input:
    needs: install-react
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          npm ci
          npm run lint
        working-directory: packages/react-json-input
  build-react-json-input:
    needs: install-react
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - run: ls -l node_modules/@chocolateloverraj
      - uses: actions/cache@v2
        id: cache-react-json-input
        env:
          cache-name: cache-react-json-input-2
        with:
          path: packages/react-json-input/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci
          npm run build
        working-directory:
          packages/react-json-input
  lint-antd:
    needs: build-react-json-input
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - run: ls -l node_modules/@chocolateloverraj
      - uses: actions/cache@v2
        id: cache-react-json-input
        env:
          cache-name: cache-react-json-input-2
        with:
          path: packages/react-json-input/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input') }}
      - if: steps.cache.outputs.cache-hit != 'true' || steps.cache-react-json-input.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - run: ls -l node_modules/@chocolateloverraj
      - run: ls node_modules/@chocolateloverraj/react-json-input/dist
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          npm ci
          npm run lint
        working-directory: packages/antd
  test-antd:
    needs: build-react-json-input
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-react-json-input
        with:
          path: packages/react-json-input/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('packages/react-json-input') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "No cache found"
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          npm ci
          npm run test:ci
        working-directory: packages/antd